### ISSUE TITLE
Vagrant for Windows Issue

### ISSUE THREAD

**Issue by Pan2020** [zencart/habitat#5]
I wonder if anyone using this?

![image](https://cloud.githubusercontent.com/assets/21959676/18214793/8d62f3e2-711c-11e6-9801-8fe9be48ff21.png)

Vagrant for Windows somehow having error on serve.sh file and therefore unable to get files from the git repository (no files being loaded after I typed http://zen.local/ or 172.22.22.22

![image](https://cloud.githubusercontent.com/assets/21959676/18214883/f09b8abe-711c-11e6-90d1-018cc937ff2d.png)

**Comment by drbyte** [comment]
In your habitat.yml file, can you try adding `docroot: /public` ... just in case there's a problem with it not understanding how to handle an empty value for that?

```diff
sites:
  - domain: zen.local
    dir: v160
    skeleton: apache.default
+   docroot: /public
    git_url: https://github.com/zencart/zencart.git
    branch: v160
```

(Don't include the `+` shown at the start of the line. That's just to make it show in green so you know where to put it.)

**Comment by Pan2020** [comment]
Edited file

![image](https://cloud.githubusercontent.com/assets/21959676/18216455/cb69926a-7124-11e6-9f4b-5d1859b95192.png)

Done the provision, still no good...

![image](https://cloud.githubusercontent.com/assets/21959676/18216458/d9add4c6-7124-11e6-9706-82e388740116.png)

I suspect something is wrong on serve.sh file. Is library changed or may need code adjustment?

**Comment by drbyte** [comment]
There's no library to update.

But it might be that the line-endings in the serve.sh file have been mangled (windows vs linux challenge).  So you could try opening serve.sh in notepad++ and add a blank line to the bottom of the file (just so something is changed), and re-save it. Then try reprovisioning.

(I don't have a Windows box to test this on, else I'd research further before making various suggestions.)

**Comment by zcwilt** [comment]
I have a windows laptop that I run habitat/vagrant on with no problems.
Although it is possible I did edit serve.sh, I can't remember doing so.
